server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa001?serverTimezone=GMT%2B8
    username: root
    password: 16851188
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
version: UserProvider02